---
- hosts: localhost
  roles:
    - {
        role: 'kraken.config',
        tags: [ 'always', 'config_only' ]
      }
    - {
        role: 'roles/kraken.services',
        tags: [ 'services', 'all' ]
      }
    - {
        role: 'roles/kraken.provider/kraken.provider.selector',
        tags: [ 'provider', 'all', ]
      }
    - {
        role: 'roles/kraken.clean',
        tags: [ 'dryrun', 'all' ]
      }
