---
- hosts: localhost
  roles:
    - {
        role: 'kraken.config', config_file: "{{ config_path | default('') }}",
        tags: [ 'always', 'config_only' ]
      }
    - {
        role: 'roles/kraken.cluster_common',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.fabric/kraken.fabric.selector',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.nodePool/kraken.nodePool.selector',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.assembler',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun'  ]
      }
    - {
        role: 'roles/kraken.provider/kraken.provider.selector',
        tags: [ 'provider', 'ssh', 'readiness', 'services', 'all' ]
      }
    - {
        role: 'roles/kraken.ssh/kraken.ssh.selector',
        tags: [ 'ssh', 'all' ]
      }
    - {
        role: 'roles/kraken.readiness',
        tags: [ 'readiness', 'services', 'all' ]
      }
