---
- name: clean the generated folder
  file:
    path: "{{ cluster_dir }}"
    state: absent
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  vars:
    cluster_dir: "{{ (config_base + '/' + a_cluster.name) | realpath }}"
    real_base_dir: "{{ ( config_base | realpath ) }}"
  # Ensure this is a subdirectory of config_base and ensure config_base is not empty or root.
  when: (( cluster_dir | dirname ) == real_base_dir ) and
        ( not ( real_base_dir | is_empty )) and
        ( not ( real_base_dir == "/" ))

  # Ensure that do not delete the cluster.status.lock file during dryrun test.
- name: clean the cluster.status.lock file
  file:
    path: "{{ config_base | expanduser }}/cluster.status.lock"
    state: absent
  when: not ( dryrun | bool )
